### ISSUE TITLE
bin/verticapylab missed the declaration for the argument v as the info of usage

### ISSUE THREAD

**Issue by dingqiangliu** [vertica/VerticaPyLab#243]
The script `bin/verticapylab` is missed the declaration for the argument  **v** as the info of usage.

https://github.com/vertica/VerticaPyLab/blob/c8fb0da74aa62d1f9b6dc7ab99eda3a400731f1d/bin/verticapylab#L34

Here is a suggestion fix:
```diff
diff --git a/bin/verticapylab b/bin/verticapylab
index 643ecee..b81b078 100755
--- a/bin/verticapylab
+++ b/bin/verticapylab
@@ -31,7 +31,7 @@ function usage {
     exit 1
 }

-while getopts "p:c:i:h" opt; do
+while getopts "p:c:v:i:h" opt; do
     case ${opt} in
         h)
             usage
```

**Comment by roypaulin** [comment]
Hi @dingqiangliu , I will address it this week with other issues you brought up.

**Comment by roypaulin** [comment]
#245
