### ISSUE TITLE
QueryProfiler UI can not get query plan according to transaction & statement

### ISSUE THREAD

**Issue by dingqiangliu** [vertica/VerticaPyLab#246]
The root cause is the `transactions` parameter of verticapy.performance.vertica.QueryProfiler requires integer type of transaction_id and statement_id, but current implement of /project/ui/qprof-ui.ipynb set  string type of them:
https://github.com/vertica/VerticaPyLab/blob/aad20d988367fe50764be08387768a137c06350c/project/ui/qprof-ui.ipynb#L52

So QueryProfiler._set_request_qd can not search them in database at here:
https://github.com/vertica/VerticaPy/blob/15cba4776fa010991586be30e66a35b190befe32/verticapy/performance/vertica/qprof.py#L1531

Here is the simple fix:
```diff
diff --git a/project/ui/qprof-ui.ipynb b/project/ui/qprof-ui.ipynb
index b33e4d6..fa0da54 100644
--- a/project/ui/qprof-ui.ipynb
+++ b/project/ui/qprof-ui.ipynb
@@ -49,7 +49,7 @@
     "        )\n",
     "    elif \"transaction_val\" in globals():\n",
     "        qprof = QueryProfilerInterface(\n",
-    "            transactions = (transaction_val, statement_val),\n",
+    "            transactions = (int(transaction_val), int(statement_val)),\n",
     "            target_schema = target_schema_val_2 if \"target_schema_val_2\" in globals() else None,\n",
     "            key_id = key_val_2 if \"key_val_2\" in globals() else None,\n",
     "        )\n",
```

**Comment by roypaulin** [comment]
@mail4umar have you seen this?

**Comment by mail4umar** [comment]
I may have missed this. but I made significant changes to make the whole application robust. @dingqiangliu please let us know if this was not resolved. 

I will be closing this now. I can reopen once there is a reply.
